################################################################################################
#                                                                                              #
#                              Copyright nezxenka && FlimixST                                  #
#                                    StrictKits 2.0                                            #
#                                                                                              #
################################################################################################

#Этот плагин поддерживает PlaceholderAPI
#https://www.spigotmc.org/resources/placeholderapi.6245/
#Не обязательно)

#Настройки хранилища вынесены в database.yml

settings:
  #Установите для этого параметра значение true, если вы хотите, чтобы /kit был меню.
  enable-gui-kit-displaying: false
  #true, если вы хотите предварительно просмотреть комплект, щелкнув элемент правой кнопкой мыши (опция выше должна быть включена)
  enable-gui-kit-previewing: false
  #Наборы по-прежнему будут отображаться в меню /kit, даже если у вас нет разрешения.
  kit-display-without-perm: true
  #Кулдаун между использованиями команд, миллисекунды. Защита от флуда на большом онлайне.
  command-throttle-millis: 250
  #Обновлять открытое меню китов раз в N тиков (0 - выключить)
  gui-refresh-ticks: 40

gui:
  rows: 6

permission:
  #Если true --> у игрока должно быть разрешение strictkits.list, чтобы получить список всех форм | Если false --> Для получения списка всех наборов не требуется разрешения.
  kit-list: false
  #Если true --> у игрока должно быть разрешение strictkits.preview для предварительного просмотра комплекта | Если false --> Для предварительного просмотра комплекта разрешение не требуется.
  kit-preview: false

GUItems:
  ExitButton:
    ==: org.bukkit.inventory.ItemStack
    type: STONE_BUTTON
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §cВыход
      lore:
        - '§6Нажми лкм чтобы выйти'
  PreviousButton:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §eНазад
  NextButton:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §eВперёд
