################################################################################################
#                                                                                              #
#                                   Copyright nezxenka                                         #
#                                     StrictKits ${version}                                           #
#                                                                                              #
################################################################################################

storage:
  type: SQLITE

  table-prefix: "strictkits_"

  sqlite:
    file: "data.db"
    journal-mode: WAL
    synchronous: NORMAL

  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "strictkits"
    username: "root"
    password: ""
    use-ssl: false
    properties:
      characterEncoding: "utf8"
      rewriteBatchedStatements: "true"
    pool:
      maximum-pool-size: 4
      minimum-idle: 1
      connection-timeout: 5000
      max-lifetime: 1800000

migration:
  import-legacy-yaml: true
